language: node_js
node_js:
  - '9.11.1'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --base-href /dev-cheatsheet-ui/
  - mv dist/dev-cheatsheet-ui/index.html dist/dev-cheatsheet-ui/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/dev-cheat-sheets
  on:
    branch: master