language: node_js
node_js:
- '9.11.1'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - stagingdeployment
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: "O/B6VxFdNxt91MMLNkcygqUp/QFiqsciwq+q5qW0lROOZHgzcQy90FLrsUn7luS9JA1uRTNR3TdAgmoGcmOtktcUjed/ugEpXoTv+WSsE8vIaMR3xTbQVy9xFRVeehz0kVIVKsnvP7QRqZdTMp7iB0Dprh3Cp/7/oqgJrFhto/Fy3nXf1Vc7LpCEMklXDdry/evGot3NthEPIhi7sOzOjCNgfvN6j7cANGfddr8W4yuQWY8WCGsGeWBt9cOAirtIQFozpDHFOMvPf+Xqs0bPWXi1f/vo/JTxTSVIxWbj6UepC9RBBg2ILqSPQLUxtWfz0e3Tdg/Ytq8VUUUrr7YEs0OEsSIXiLj9A40fJ1FA9lHxqsJzKwGQVpvAr/4qwQTdVYACnGkiadTpdaDW4g8nl1I0MrHlcx5PiZyJwjZYDKbI0JK98q9hXL54SORhQW5dMqZGcP4xvp1dkL4n/Gdfg00NoYP8RQSkPiZ+7/Dp4hxvpIeTto7k26hW31Eh8GAk9+uKz0hLVKVg64heZBm8P+ZHqWU/WWGXf9A1vIoe6cpymAfVzzipzZFnk0ztty+l9OUJIGVw+SBT6kh+uRHmYs2mBXsKLJcbpJzOLiYqoATZNtoS9lt3phVXoGH7WPtOmEAtlBNBiIXZdP7wER+m3M8G8TpH0XE/6MuyrndJbp4="
  app: dev-cheat-sheets