language: node_js
node_js:
- '9.11.1'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: "Ks0XzvapZksBkfIlzO2rQ5AmSACkZVXaSWubfmTnK2BDf3S3vnd3ENlGffUO6R8sjeD75xuPDZ6KeQudSp6KqKtXXbcCoEt/1MaNbvGmerB+Yfe9hFRDlm/xvaZG7JiKXwVZ8Ul+tUnMUsqEEaGGnJQgY+t7DnR1VQFespC2XYSHRHeTVjJ7GOYud00tIKSMs0JIO1U+9Os3Io0Y/HmunuoFTlTwzwYZlkFstI/ZhTb11GZza6kMh4oSFQDAzFfLx8TgReR7mLUmYRDSzFhI3jimMYxBkBY9lf2xRO2NQXOTHwbd72uZMzcarzhok4V+jiaNaA6Z07q52Inu3e4CV2W0E00cXJeVhRcz5sTXXr2Y2n3JKjVKV2w/TqhekpWDGWh8in2VIWx/JBb5QPK4ejGL1/Hq5xgg5fEB9eahZdr8+LYppSLSUYdUS1s3v7q0Prz/HE2XiLloMIkL+nl1tfaVrDAhklihHQvpznCoetpIJ40t5l8PRqTnAHmVO5u4+0z+VwzqKVCd46yYGbkW0iTzTrmKIRO47vbYcc70VqHF3HU7FSmrCqU6GCoDg8DuXUnxuY8Gw04k9QemNhxu8mtlBOpr3YX4ltMXTdzAshO++MGE3gK4f0bCZpmBeA9WowQv6vkrnRmqv+iY5uNUYb7e5P1rPpWNNxZmrDHFk3Y="
  app: dev-cheat-sheets