language: node_js
node_js:
- '9.11.1'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - stagingdeployment
after_script:
- chmod +x publish-gh-pages.sh && ./publish-gh-pages.sh
deploy:
  provider: heroku
  api_key:
    secure: "lrEeicOBCqCoXQeq/Fx1bRLKfnwq+ddpFK7KQn8fMW+TU7dtQtrQIg1fHsNJ+4t1+9Wu9ck/6KdEOHIG3jx8zWYQm+n9Y0QbJIAri4mf/7XJAlYHe0lK7HZT8sLadeAP3FauI8xrf5/bL9lRPVG0afCsRNRG1BjqAqZPXo/huUxAdD7/3gqUk2w6073pO/Uxn0ilsJBTbqVgD5IERLa7v6025H9uuZfX99IM1bhx1QNnBjj8XQBs32/wOoL2oA9BAEVEq8PKdP+AuDFwORdzPvaQPLqnv2f7aVfltYRRAoH9t7PElPK2JFXauVAGhNmrTJixWAPy326ILrL1I4MPddoLxqAanLe4rXbDlGWN1nB7gb9cnxxtf+yi+wZJ6MAcJZ5PCr9W5HpAFXrV1nlY0wQK4pLCc0l5DlvFS5A5V8GiBPjHROCpaRATwiGgGqxO0RILoY12TqpKN924fcGAsG4Tr2QUYC6wkxBXMr2fhXE69POZzzcAWyH5SIIu+z85r3Wh4PTFqy3w7712my4gJfRdWQiidoWqqeP2HhDz0O8dbu1sOQrP2KXVPNF8ab0QOsjBBFBG4Pc/MQHuKYi9CC1/v/1u9ICwkGgjFkwNg4oD6NmSRQah3y/03g86TIH5BfZIrWlCRYbUU9YVgbYTF/WSp+CEV56ZxfhXDwZ9lzQ="
  app: dev-cheat-sheets